// export const robots = [
//   {
//     id: 1,
//     name: 'Leanne Graham',
//     username: 'Bret',
//     email: 'Sincere@april.biz'
//   },
//   {
//     id: 2,
//     name: 'Ervin Howell',
//     username: 'Antonette',
//     email: 'Shanna@melissa.tv'
//   },
//   {
//     id: 3,
//     name: 'Clementine Bauch',
//     username: 'Samantha',
//     email: 'Nathan@yesenia.net'
//   },
//   {
//     id: 4,
//     name: 'Patricia Lebsack',
//     username: 'Karianne',
//     email: 'Julianne.OConner@kory.org'
//   },
//   {
//     id: 5,
//     name: 'Chelsey Dietrich',
//     username: 'Kamren',
//     email: 'Lucio_Hettinger@annie.ca'
//   },
//   {
//     id: 6,
//     name: 'Mrs. Dennis Schulist',
//     username: 'Leopoldo_Corkery',
//     email: 'Karley_Dach@jasper.info'
//   },
//   {
//     id: 7,
//     name: 'Kurtis Weissnat',
//     username: 'Elwyn.Skiles',
//     email: 'Telly.Hoeger@billy.biz'
//   },
//   {
//     id: 8,
//     name: 'Nicholas Runolfsdottir V',
//     username: 'Maxime_Nienow',
//     email: 'Sherwood@rosamond.me'
//   },
//   {
//     id: 9,
//     name: 'Glenna Reichert',
//     username: 'Delphine',
//     email: 'Chaim_McDermott@dana.io'
//   },
//   {
//     id: 10,
//     name: 'Clementina DuBuque',
//     username: 'Moriah.Stanton',
//     email: 'Rey.Padberg@karina.biz'
//   }
// ];


// export const robots = [
//   {
//     name: "Luke Skywalker",
//     image: "a",
//     height: "172",
//     mass: "77",
//     : "blond",
//     skin_color: "fair",
//     eye_color: "blue",
//     birth_year: "19BBY",
//     gender: "male",
//     homeworld: "https://swapi.py4e.com/api/planets/1/",
//   },
//   {
//     name: "C-3PO",
//     height: "167",
//     image: "b",
//     mass: "75",
//     : "n/a",
//     skin_color: "gold",
//     eye_color: "yellow",
//     birth_year: "112BBY",
//     gender: "n/a",
//     homeworld: "https://swapi.py4e.com/api/planets/1/",
//   },
//   {
//     name: "R2-D2",
//     height: "96",
//     image: "c",
//     mass: "32",
//     : "n/a",
//     skin_color: "white, blue",
//     eye_color: "red",
//     birth_year: "33BBY",
//     gender: "n/a",
//     homeworld: "https://swapi.py4e.com/api/planets/8/",
//     films: [
//       "https://swapi.py4e.com/api/films/1/",
//       "https://swapi.py4e.com/api/films/2/",
//       "https://swapi.py4e.com/api/films/3/",
//       "https://swapi.py4e.com/api/films/4/",
//       "https://swapi.py4e.com/api/films/5/",
//       "https://swapi.py4e.com/api/films/6/",
//       "https://swapi.py4e.com/api/films/7/"
//     ],
//     species: [
//       "https://swapi.py4e.com/api/species/2/"
//     ],
//     vehicles: [],
//     starships: [],
//     created: "2014-12-10T15:11:50.376000Z",
//     edited: "2014-12-20T21:17:50.311000Z",
//     url: "https://swapi.py4e.com/api/people/3/"
//   },
//   {
//     name: "Darth Vader",
//     height: "202",
//     image: "d",
//     mass: "136",
//     : "none",
//     skin_color: "white",
//     eye_color: "yellow",
//     birth_year: "41.9BBY",
//     gender: "male",
//     homeworld: "https://swapi.py4e.com/api/planets/1/",
//     films: [
//       "https://swapi.py4e.com/api/films/1/",
//       "https://swapi.py4e.com/api/films/2/",
//       "https://swapi.py4e.com/api/films/3/",
//       "https://swapi.py4e.com/api/films/6/"
//     ],
//     species: [
//       "https://swapi.py4e.com/api/species/1/"
//     ],
//     vehicles: [],
//     starships: [
//       "https://swapi.py4e.com/api/starships/13/"
//     ],
//     created: "2014-12-10T15:18:20.704000Z",
//     edited: "2014-12-20T21:17:50.313000Z",
//     url: "https://swapi.py4e.com/api/people/4/"
//   }
// ];

export const robots = [
  {
        "date": "2022-10-28",
        "date_epoch": 1666915200,
            "maxtemp_c": 13.0,
            "maxtemp_f": 55.4,
            "mintemp_c": 10.2,
            "mintemp_f": 50.4,
            "avgtemp_c": 11.9,
            "avgtemp_f": 53.5,
            "maxwind_mph": 4.7,
            "maxwind_kph": 7.6,
            "totalprecip_mm": 2.5,
            "totalprecip_in": 0.1,
            "totalsnow_cm": 0.0,
            "avgvis_km": 7.5,
            "avgvis_miles": 4.0,
            "avghumidity": 81.0,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 81,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
            },
            "uv": 3.0,
        "astro": {
            "sunrise": "07:46 AM",
            "sunset": "06:04 PM",
            "moonrise": "11:54 AM",
            "moonset": "08:10 PM",
            "moon_phase": "Waxing Crescent",
            "moon_illumination": "18"
        },
        "hour": [
            {
                "time_epoch": 1666940400,
                "time": "2022-10-28 00:00",
                "temp_c": 11.1,
                "temp_f": 52.0,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 2.5,
                "wind_kph": 4.0,
                "wind_degree": 175,
                "wind_dir": "S",
                "pressure_mb": 1017.0,
                "pressure_in": 30.02,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 61,
                "cloud": 99,
                "feelslike_c": 10.9,
                "feelslike_f": 51.6,
                "windchill_c": 10.9,
                "windchill_f": 51.6,
                "heatindex_c": 11.1,
                "heatindex_f": 52.0,
                "dewpoint_c": 4.0,
                "dewpoint_f": 39.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 4.0,
                "gust_kph": 6.5,
                "uv": 1.0
            },
            {
                "time_epoch": 1666944000,
                "time": "2022-10-28 01:00",
                "temp_c": 10.8,
                "temp_f": 51.4,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 2.7,
                "wind_kph": 4.3,
                "wind_degree": 164,
                "wind_dir": "SSE",
                "pressure_mb": 1017.0,
                "pressure_in": 30.02,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 61,
                "cloud": 100,
                "feelslike_c": 10.1,
                "feelslike_f": 50.2,
                "windchill_c": 10.1,
                "windchill_f": 50.2,
                "heatindex_c": 10.8,
                "heatindex_f": 51.4,
                "dewpoint_c": 3.6,
                "dewpoint_f": 38.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 4.5,
                "gust_kph": 7.2,
                "uv": 1.0
            },
            {
                "time_epoch": 1666947600,
                "time": "2022-10-28 02:00",
                "temp_c": 10.2,
                "temp_f": 50.4,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 4.3,
                "wind_kph": 6.8,
                "wind_degree": 143,
                "wind_dir": "SE",
                "pressure_mb": 1018.0,
                "pressure_in": 30.05,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 79,
                "cloud": 100,
                "feelslike_c": 9.4,
                "feelslike_f": 48.9,
                "windchill_c": 9.4,
                "windchill_f": 48.9,
                "heatindex_c": 10.2,
                "heatindex_f": 50.4,
                "dewpoint_c": 6.7,
                "dewpoint_f": 44.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.2,
                "gust_kph": 11.5,
                "uv": 1.0
            },
            {
                "time_epoch": 1666951200,
                "time": "2022-10-28 03:00",
                "temp_c": 10.3,
                "temp_f": 50.5,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 3.8,
                "wind_kph": 6.1,
                "wind_degree": 165,
                "wind_dir": "SSE",
                "pressure_mb": 1017.0,
                "pressure_in": 30.03,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 78,
                "cloud": 100,
                "feelslike_c": 9.4,
                "feelslike_f": 48.9,
                "windchill_c": 9.4,
                "windchill_f": 48.9,
                "heatindex_c": 10.3,
                "heatindex_f": 50.5,
                "dewpoint_c": 6.6,
                "dewpoint_f": 43.9,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 6.3,
                "gust_kph": 10.1,
                "uv": 1.0
            },
            {
                "time_epoch": 1666954800,
                "time": "2022-10-28 04:00",
                "temp_c": 10.8,
                "temp_f": 51.4,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 4.0,
                "wind_kph": 6.5,
                "wind_degree": 168,
                "wind_dir": "SSE",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 74,
                "cloud": 100,
                "feelslike_c": 9.8,
                "feelslike_f": 49.6,
                "windchill_c": 9.8,
                "windchill_f": 49.6,
                "heatindex_c": 10.8,
                "heatindex_f": 51.4,
                "dewpoint_c": 6.4,
                "dewpoint_f": 43.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 6.7,
                "gust_kph": 10.8,
                "uv": 1.0
            },
            {
                "time_epoch": 1666958400,
                "time": "2022-10-28 05:00",
                "temp_c": 11.1,
                "temp_f": 52.0,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 4.0,
                "wind_kph": 6.5,
                "wind_degree": 171,
                "wind_dir": "S",
                "pressure_mb": 1016.0,
                "pressure_in": 30.0,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 71,
                "cloud": 94,
                "feelslike_c": 9.8,
                "feelslike_f": 49.6,
                "windchill_c": 9.8,
                "windchill_f": 49.6,
                "heatindex_c": 11.1,
                "heatindex_f": 52.0,
                "dewpoint_c": 6.1,
                "dewpoint_f": 43.0,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 6.9,
                "gust_kph": 11.2,
                "uv": 1.0
            },
            {
                "time_epoch": 1666962000,
                "time": "2022-10-28 06:00",
                "temp_c": 11.6,
                "temp_f": 52.9,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 4.7,
                "wind_kph": 7.6,
                "wind_degree": 164,
                "wind_dir": "SSE",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 69,
                "cloud": 96,
                "feelslike_c": 10.0,
                "feelslike_f": 50.0,
                "windchill_c": 10.0,
                "windchill_f": 50.0,
                "heatindex_c": 11.6,
                "heatindex_f": 52.9,
                "dewpoint_c": 6.0,
                "dewpoint_f": 42.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.5,
                "gust_kph": 13.7,
                "uv": 1.0
            },
            {
                "time_epoch": 1666965600,
                "time": "2022-10-28 07:00",
                "temp_c": 12.0,
                "temp_f": 53.6,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 4.3,
                "wind_kph": 6.8,
                "wind_degree": 179,
                "wind_dir": "S",
                "pressure_mb": 1017.0,
                "pressure_in": 30.03,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 67,
                "cloud": 91,
                "feelslike_c": 10.2,
                "feelslike_f": 50.4,
                "windchill_c": 10.2,
                "windchill_f": 50.4,
                "heatindex_c": 12.0,
                "heatindex_f": 53.6,
                "dewpoint_c": 6.0,
                "dewpoint_f": 42.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.8,
                "gust_kph": 12.6,
                "uv": 1.0
            },
            {
                "time_epoch": 1666969200,
                "time": "2022-10-28 08:00",
                "temp_c": 12.3,
                "temp_f": 54.1,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 3.6,
                "wind_kph": 5.8,
                "wind_degree": 210,
                "wind_dir": "SSW",
                "pressure_mb": 1017.0,
                "pressure_in": 30.03,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 66,
                "cloud": 98,
                "feelslike_c": 10.5,
                "feelslike_f": 50.9,
                "windchill_c": 10.5,
                "windchill_f": 50.9,
                "heatindex_c": 12.3,
                "heatindex_f": 54.1,
                "dewpoint_c": 6.2,
                "dewpoint_f": 43.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 5.8,
                "gust_kph": 9.4,
                "uv": 3.0
            },
            {
                "time_epoch": 1666972800,
                "time": "2022-10-28 09:00",
                "temp_c": 12.6,
                "temp_f": 54.7,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 2.5,
                "wind_kph": 4.0,
                "wind_degree": 327,
                "wind_dir": "NNW",
                "pressure_mb": 1017.0,
                "pressure_in": 30.04,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 66,
                "cloud": 93,
                "feelslike_c": 10.8,
                "feelslike_f": 51.4,
                "windchill_c": 10.8,
                "windchill_f": 51.4,
                "heatindex_c": 12.6,
                "heatindex_f": 54.7,
                "dewpoint_c": 6.4,
                "dewpoint_f": 43.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 2.0,
                "vis_miles": 1.0,
                "gust_mph": 3.4,
                "gust_kph": 5.4,
                "uv": 3.0
            },
            {
                "time_epoch": 1666976400,
                "time": "2022-10-28 10:00",
                "temp_c": 12.1,
                "temp_f": 53.8,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 2.0,
                "wind_kph": 3.2,
                "wind_degree": 85,
                "wind_dir": "E",
                "pressure_mb": 1018.0,
                "pressure_in": 30.07,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 75,
                "cloud": 100,
                "feelslike_c": 10.4,
                "feelslike_f": 50.7,
                "windchill_c": 10.4,
                "windchill_f": 50.7,
                "heatindex_c": 12.1,
                "heatindex_f": 53.8,
                "dewpoint_c": 7.9,
                "dewpoint_f": 46.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 2.0,
                "vis_miles": 1.0,
                "gust_mph": 2.7,
                "gust_kph": 4.3,
                "uv": 3.0
            },
            {
                "time_epoch": 1666980000,
                "time": "2022-10-28 11:00",
                "temp_c": 11.8,
                "temp_f": 53.2,
                "is_day": 1,
                "condition": {
                    "text": "Light rain",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                    "code": 1183
                },
                "wind_mph": 1.8,
                "wind_kph": 2.9,
                "wind_degree": 80,
                "wind_dir": "E",
                "pressure_mb": 1019.0,
                "pressure_in": 30.08,
                "precip_mm": 1.5,
                "precip_in": 0.06,
                "humidity": 87,
                "cloud": 100,
                "feelslike_c": 10.1,
                "feelslike_f": 50.2,
                "windchill_c": 10.1,
                "windchill_f": 50.2,
                "heatindex_c": 11.8,
                "heatindex_f": 53.2,
                "dewpoint_c": 9.8,
                "dewpoint_f": 49.6,
                "will_it_rain": 0,
                "chance_of_rain": 61,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 7.0,
                "vis_miles": 4.0,
                "gust_mph": 2.2,
                "gust_kph": 3.6,
                "uv": 3.0
            },
            {
                "time_epoch": 1666983600,
                "time": "2022-10-28 12:00",
                "temp_c": 12.1,
                "temp_f": 53.8,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 2.2,
                "wind_kph": 3.6,
                "wind_degree": 106,
                "wind_dir": "ESE",
                "pressure_mb": 1020.0,
                "pressure_in": 30.11,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 88,
                "cloud": 100,
                "feelslike_c": 10.7,
                "feelslike_f": 51.3,
                "windchill_c": 10.7,
                "windchill_f": 51.3,
                "heatindex_c": 12.1,
                "heatindex_f": 53.8,
                "dewpoint_c": 10.2,
                "dewpoint_f": 50.4,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 2.0,
                "vis_miles": 1.0,
                "gust_mph": 2.9,
                "gust_kph": 4.7,
                "uv": 3.0
            },
            {
                "time_epoch": 1666987200,
                "time": "2022-10-28 13:00",
                "temp_c": 12.3,
                "temp_f": 54.1,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 1.8,
                "wind_kph": 2.9,
                "wind_degree": 130,
                "wind_dir": "SE",
                "pressure_mb": 1020.0,
                "pressure_in": 30.11,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 90,
                "cloud": 100,
                "feelslike_c": 11.0,
                "feelslike_f": 51.8,
                "windchill_c": 11.0,
                "windchill_f": 51.8,
                "heatindex_c": 12.3,
                "heatindex_f": 54.1,
                "dewpoint_c": 10.6,
                "dewpoint_f": 51.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 2.0,
                "vis_miles": 1.0,
                "gust_mph": 2.2,
                "gust_kph": 3.6,
                "uv": 3.0
            },
            {
                "time_epoch": 1666990800,
                "time": "2022-10-28 14:00",
                "temp_c": 12.6,
                "temp_f": 54.7,
                "is_day": 1,
                "condition": {
                    "text": "Light rain",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                    "code": 1183
                },
                "wind_mph": 2.0,
                "wind_kph": 3.2,
                "wind_degree": 150,
                "wind_dir": "SSE",
                "pressure_mb": 1020.0,
                "pressure_in": 30.12,
                "precip_mm": 1.0,
                "precip_in": 0.04,
                "humidity": 90,
                "cloud": 100,
                "feelslike_c": 11.4,
                "feelslike_f": 52.5,
                "windchill_c": 11.4,
                "windchill_f": 52.5,
                "heatindex_c": 12.6,
                "heatindex_f": 54.7,
                "dewpoint_c": 11.0,
                "dewpoint_f": 51.8,
                "will_it_rain": 1,
                "chance_of_rain": 81,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 9.0,
                "vis_miles": 5.0,
                "gust_mph": 2.5,
                "gust_kph": 4.0,
                "uv": 3.0
            },
            {
                "time_epoch": 1666994400,
                "time": "2022-10-28 15:00",
                "temp_c": 13.0,
                "temp_f": 55.4,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 1.6,
                "wind_kph": 2.5,
                "wind_degree": 152,
                "wind_dir": "SSE",
                "pressure_mb": 1020.0,
                "pressure_in": 30.13,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 89,
                "cloud": 100,
                "feelslike_c": 11.8,
                "feelslike_f": 53.2,
                "windchill_c": 11.8,
                "windchill_f": 53.2,
                "heatindex_c": 13.0,
                "heatindex_f": 55.4,
                "dewpoint_c": 11.2,
                "dewpoint_f": 52.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 2.0,
                "vis_miles": 1.0,
                "gust_mph": 2.0,
                "gust_kph": 3.2,
                "uv": 3.0
            },
            {
                "time_epoch": 1666998000,
                "time": "2022-10-28 16:00",
                "temp_c": 13.0,
                "temp_f": 55.4,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 1.3,
                "wind_kph": 2.2,
                "wind_degree": 171,
                "wind_dir": "S",
                "pressure_mb": 1021.0,
                "pressure_in": 30.14,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 89,
                "cloud": 100,
                "feelslike_c": 11.7,
                "feelslike_f": 53.1,
                "windchill_c": 11.7,
                "windchill_f": 53.1,
                "heatindex_c": 13.0,
                "heatindex_f": 55.4,
                "dewpoint_c": 11.2,
                "dewpoint_f": 52.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 2.0,
                "vis_miles": 1.0,
                "gust_mph": 1.8,
                "gust_kph": 2.9,
                "uv": 3.0
            },
            {
                "time_epoch": 1667001600,
                "time": "2022-10-28 17:00",
                "temp_c": 13.0,
                "temp_f": 55.4,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 0.7,
                "wind_kph": 1.1,
                "wind_degree": 155,
                "wind_dir": "SSE",
                "pressure_mb": 1021.0,
                "pressure_in": 30.15,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 89,
                "cloud": 100,
                "feelslike_c": 11.8,
                "feelslike_f": 53.2,
                "windchill_c": 11.8,
                "windchill_f": 53.2,
                "heatindex_c": 13.0,
                "heatindex_f": 55.4,
                "dewpoint_c": 11.2,
                "dewpoint_f": 52.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 2.0,
                "vis_miles": 1.0,
                "gust_mph": 0.9,
                "gust_kph": 1.4,
                "uv": 3.0
            },
            {
                "time_epoch": 1667005200,
                "time": "2022-10-28 18:00",
                "temp_c": 12.9,
                "temp_f": 55.2,
                "is_day": 1,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 0.2,
                "wind_kph": 0.4,
                "wind_degree": 36,
                "wind_dir": "NE",
                "pressure_mb": 1021.0,
                "pressure_in": 30.16,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 89,
                "cloud": 100,
                "feelslike_c": 11.8,
                "feelslike_f": 53.2,
                "windchill_c": 11.8,
                "windchill_f": 53.2,
                "heatindex_c": 12.9,
                "heatindex_f": 55.2,
                "dewpoint_c": 11.1,
                "dewpoint_f": 52.0,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 0.2,
                "gust_kph": 0.4,
                "uv": 3.0
            },
            {
                "time_epoch": 1667008800,
                "time": "2022-10-28 19:00",
                "temp_c": 12.4,
                "temp_f": 54.3,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 0.7,
                "wind_kph": 1.1,
                "wind_degree": 46,
                "wind_dir": "NE",
                "pressure_mb": 1022.0,
                "pressure_in": 30.19,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 89,
                "cloud": 100,
                "feelslike_c": 11.3,
                "feelslike_f": 52.3,
                "windchill_c": 11.3,
                "windchill_f": 52.3,
                "heatindex_c": 12.4,
                "heatindex_f": 54.3,
                "dewpoint_c": 10.6,
                "dewpoint_f": 51.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 0.9,
                "gust_kph": 1.4,
                "uv": 1.0
            },
            {
                "time_epoch": 1667012400,
                "time": "2022-10-28 20:00",
                "temp_c": 12.4,
                "temp_f": 54.3,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 0.9,
                "wind_kph": 1.4,
                "wind_degree": 72,
                "wind_dir": "ENE",
                "pressure_mb": 1023.0,
                "pressure_in": 30.2,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 89,
                "cloud": 100,
                "feelslike_c": 11.6,
                "feelslike_f": 52.9,
                "windchill_c": 11.6,
                "windchill_f": 52.9,
                "heatindex_c": 12.4,
                "heatindex_f": 54.3,
                "dewpoint_c": 10.6,
                "dewpoint_f": 51.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 1.3,
                "gust_kph": 2.2,
                "uv": 1.0
            },
            {
                "time_epoch": 1667016000,
                "time": "2022-10-28 21:00",
                "temp_c": 12.2,
                "temp_f": 54.0,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 1.1,
                "wind_kph": 1.8,
                "wind_degree": 45,
                "wind_dir": "NE",
                "pressure_mb": 1023.0,
                "pressure_in": 30.22,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 90,
                "cloud": 100,
                "feelslike_c": 11.6,
                "feelslike_f": 52.9,
                "windchill_c": 11.6,
                "windchill_f": 52.9,
                "heatindex_c": 12.2,
                "heatindex_f": 54.0,
                "dewpoint_c": 10.7,
                "dewpoint_f": 51.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 1.6,
                "gust_kph": 2.5,
                "uv": 1.0
            },
            {
                "time_epoch": 1667019600,
                "time": "2022-10-28 22:00",
                "temp_c": 12.0,
                "temp_f": 53.6,
                "is_day": 0,
                "condition": {
                    "text": "Overcast",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 0.9,
                "wind_kph": 1.4,
                "wind_degree": 34,
                "wind_dir": "NE",
                "pressure_mb": 1024.0,
                "pressure_in": 30.24,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 93,
                "cloud": 100,
                "feelslike_c": 11.6,
                "feelslike_f": 52.9,
                "windchill_c": 11.6,
                "windchill_f": 52.9,
                "heatindex_c": 12.0,
                "heatindex_f": 53.6,
                "dewpoint_c": 10.9,
                "dewpoint_f": 51.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 1.3,
                "gust_kph": 2.2,
                "uv": 1.0
            },
            {
                "time_epoch": 1667023200,
                "time": "2022-10-28 23:00",
                "temp_c": 11.8,
                "temp_f": 53.2,
                "is_day": 0,
                "condition": {
                    "text": "Mist",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                    "code": 1030
                },
                "wind_mph": 0.7,
                "wind_kph": 1.1,
                "wind_degree": 52,
                "wind_dir": "NE",
                "pressure_mb": 1024.0,
                "pressure_in": 30.25,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 96,
                "cloud": 100,
                "feelslike_c": 11.9,
                "feelslike_f": 53.4,
                "windchill_c": 11.9,
                "windchill_f": 53.4,
                "heatindex_c": 11.8,
                "heatindex_f": 53.2,
                "dewpoint_c": 11.2,
                "dewpoint_f": 52.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 0.9,
                "gust_kph": 1.4,
                "uv": 1.0
            }
        ]
    }
]